### PR TITLE
Fix rviz trajectory rendering crash

### LINKED ISSUE #366: Trajectory visualization crashes
RViz crashes after a while when trajectory visualization is enabled.

Reading through the RViz code it seems the line strip marker does not support lines with more than 16384 points. See
<https://github.com/ros-visualization/rviz/blob/kinetic-devel/src/rviz/ogre_helpers/billboard_line.cpp>. Maybe this is the issue?

Possible solution: Split longer trajectories into multiple line strip markers and see whether this fixes the crashes.

@ojura Do you want to try a fix? Feel free to unassign  if you would prefer me to look into it.

### PR DESCRIPTION
**Pull request by ojura**
Rviz has a limit of 16384 points per marker. To get around this, each
trajectory is split into multiple markers, each up to 16384 points.
Fixes #366.

### CODE REVIEW

File: cartographer_ros/cartographer_ros/map_builder_bridge.cc [hunk 1]
```diff
@@ -210,8 +210,18 @@ visualization_msgs::MarkerArray MapBuilderBridge::GetTrajectoryNodesList() {
...
     marker.pose.orientation.w = 1.0;
     for (const auto& node : single_trajectory) {
-      marker.points.push_back(ToGeometryMsgPoint(
-          (node.pose * node.constant_data->tracking_to_pose).translation()));
+      ::geometry_msgs::Point node_point = ToGeometryMsgPoint(
+          (node.pose * node.constant_data->tracking_to_pose).translation());
+      marker.points.push_back(node_point);
+      // Work around the 16384 point limit in rviz by splitting the
+      // trajectory into multiple markers
+      if (marker.points.size() == (1 << 14)) {
```
Comment (wohe) [inline cartographer_ros/cartographer_ros/map_builder_bridge.cc]: Consistency and readability: Please change `(1 << 14)` to `16384` to match the comment.

File: cartographer_ros/cartographer_ros/map_builder_bridge.cc [hunk 2]
```diff
@@ -210,8 +210,18 @@ visualization_msgs::MarkerArray MapBuilderBridge::GetTrajectoryNodesList() {
     marker.scale.x = kTrajectoryLineStripMarkerScale;
     marker.pose.orientation.w = 1.0;
     for (const auto& node : single_trajectory) {
-      marker.points.push_back(ToGeometryMsgPoint(
-          (node.pose * node.constant_data->tracking_to_pose).translation()));
+      ::geometry_msgs::Point node_point = ToGeometryMsgPoint(
+          (node.pose * node.constant_data->tracking_to_pose).translation());
+      marker.points.push_back(node_point);
+      // Work around the 16384 point limit in rviz by splitting the
+      // trajectory into multiple markers
```
Comment (wohe) [inline cartographer_ros/cartographer_ros/map_builder_bridge.cc]: Please end sentence with a period. Similar in the comment below.

File: cartographer_ros/cartographer_ros/map_builder_bridge.cc [hunk 3]
```diff
@@ -210,8 +210,18 @@ visualization_msgs::MarkerArray MapBuilderBridge::GetTrajectoryNodesList() {
     marker.scale.x = kTrajectoryLineStripMarkerScale;
     marker.pose.orientation.w = 1.0;
     for (const auto& node : single_trajectory) {
-      marker.points.push_back(ToGeometryMsgPoint(
-          (node.pose * node.constant_data->tracking_to_pose).translation()));
+      ::geometry_msgs::Point node_point = ToGeometryMsgPoint(
```
Comment (wohe) [inline cartographer_ros/cartographer_ros/map_builder_bridge.cc]: `const`?
